/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'abuckeridge' at '23/11/15 21:51' with Gradle 2.9
 *
 * @author abuckeridge, @date 23/11/15 21:51
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
