/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'abuckeridge' at '23/11/15 21:51' with Gradle 2.9
 *
 * @author abuckeridge, @date 23/11/15 21:51
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
